neo4j-php/neo4j-php-client

- README.md
- src/ClientBuilder.php
- src/Network/Bolt/BoltSession.php
- tests/Unit/ClientBuilderTest.php
- Fixed bug during opening bolt transaction with a non-default database
- Updated bolt connection docs
- Stricter checks when opening a transaction
> Closes #16

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
> Fixing failing cc-test-report in CI

- src/Bolt/BoltConnectionPool.php
See detailed issue: https://github.com/neo4j-php/neo4j-php-client/issues/54
> Fix condition to enable SSL

- .github/workflows/static-analysis.yml
- composer.json
- src/Bolt/BoltConfiguration.php
- src/Common/TransactionHelper.php
- src/Contracts/CypherContainerInterface.php
- src/Contracts/HasPropertiesInterface.php
- src/Types/AbstractCypherContainer.php
- src/Types/AbstractPropertyContainer.php
- src/Types/Cartesian3DPoint.php
- src/Types/CartesianPoint.php
- src/Types/CypherList.php
- src/Types/CypherMap.php
- src/Types/Date.php
- src/Types/DateTime.php
- src/Types/Duration.php
- src/Types/LocalDateTime.php
- src/Types/LocalTime.php
- src/Types/Node.php
- src/Types/Path.php
- src/Types/Relationship.php
- src/Types/Time.php
- src/Types/UnboundRelationship.php
- src/Types/WGS843DPoint.php
- src/Types/WGS84Point.php
- tests/Integration/OGMFormatterIntegrationTest.php
Streamline relationship access in cypher objects
Improve performance by caching certain translations
references #72
> Relationship streamline

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
- docker-compose.yml
- docker/docker-compose.yml
- src/Bolt/BoltConnectionPool.php
- src/Bolt/BoltDriver.php
- src/Client.php
- src/Contracts/ClientInterface.php
- src/Contracts/ConnectionPoolInterface.php
- src/Contracts/DriverInterface.php
- src/Http/HttpConnectionPool.php
- src/Http/HttpDriver.php
- src/Neo4j/Neo4jConnectionPool.php
- src/Neo4j/Neo4jDriver.php
- tests/Integration/ClientIntegrationTest.php
- tests/Integration/EnvironmentAwareIntegrationTest.php
Added new feature to check if a driver or client can create a valid connection.
See #90
> Connection management

- composer.json
- src/Basic/Driver.php
- src/Bolt/BoltConnectionPool.php
- src/Bolt/BoltDriver.php
- src/Bolt/BoltUnmanagedTransaction.php
- src/Bolt/Session.php
- src/BoltFactory.php
- src/Client.php
- src/ClientBuilder.php
- src/Common/BoltConnection.php
- src/Common/TransactionHelper.php
- src/Contracts/ConnectionInterface.php
- src/Contracts/ConnectionPoolInterface.php
- src/Databags/DriverSetup.php
- src/Databags/TransactionConfiguration.php
- src/DriverFactory.php
- src/Http/HttpConnection.php
- src/Http/HttpConnectionPool.php
- src/Http/HttpSession.php
- src/Neo4j/Neo4jConnectionPool.php
- src/Neo4j/Neo4jDriver.php
- testkit-backend/src/Handlers/NewDriver.php
- tests/Integration/ComplexQueryTest.php
- tests/Unit/BoltCypherFormatterTest.php
This PR implements correct timeout handling found in the transaction configuration
> Correct timeout usage

- src/Formatter/Specialised/BoltOGMTranslator.php
- src/Formatter/Specialised/HttpOGMTranslator.php
- src/Types/Abstract3DPoint.php
- src/Types/AbstractPoint.php
- src/Types/Cartesian3DPoint.php
- src/Types/CartesianPoint.php
- src/Types/WGS843DPoint.php
- src/Types/WGS84Point.php
This solves issue #114.
It has some backwards compatibility breaks in how the toArray of WGS84 points behave.
If you do not like that, it could be made backwards compatible, but I like it this way.
I guess some tests are broken now. Do you have tips/documentation/short summary on how to set up the local testing enviroment?
> Refactor point types

- docker-compose.yml
- psalm.xml
- src/Bolt/BoltResult.php
- tests/Integration/BoltResultIntegrationTest.php
- tests/Integration/TransactionIntegrationTest.php
> Regression fixes

- src/Formatter/Specialised/HttpOGMTranslator.php
I think I pinpointed the issue.
> Partially fix issue 120

- composer.json
- src/Types/AbstractCypherSequence.php
- tests/Integration/SummarizedResultFormatterTest.php
> Fixed error dumping and serialisation issue with unconsumed results

- src/Bolt/Session.php
- tests/Integration/ComplexQueryTest.php
> correctly propagate tx_timeout

- src/Types/AbstractCypherSequence.php
- tests/Integration/ClientIntegrationTest.php
> fixed usage of fetchSize for amount bigger than fetched size.

- src/Basic/Driver.php
- src/Bolt/BoltDriver.php
- src/Client.php
- src/Common/DriverSetupManager.php
- src/Contracts/DriverInterface.php
- src/Http/HttpDriver.php
- src/Neo4j/Neo4jDriver.php
- tests/Integration/ClientIntegrationTest.php
Fixes bug when acquire uses default session configuration, triggering a potentially unnecessary opening of connection.
> Redundant acquire bugfix

- src/Bolt/BoltConnection.php
I don't know if you want to use constants from bolt library for states. I kept strings how it was.
> Used server states from bolt library

- .gitignore
- src/Bolt/BoltUnmanagedTransaction.php
- src/BoltFactory.php
- src/Enum/ConnectionProtocol.php
- src/Formatter/OGMFormatter.php
- src/Http/HttpHelper.php
- src/ParameterHelper.php
- src/Types/DateTime.php
- tests/Integration/SummarizedResultFormatterTest.php
- tests/Unit/ParameterHelperTest.php
Finetune the parameter helper so it can pass on the correct version to packstream depending on the protocol used over the connection.
> Parameterhelper update

- src/Basic/Client.php
- src/Client.php
- src/Common/DriverSetupManager.php
- src/Contracts/ClientInterface.php
Implemented the possibility to bind multiple transactions to a client to enhance useability
Implemented transaction and Session re-usage where possible to improve performance
> Transaction client

- src/Types/AbstractCypherSequence.php
- src/Types/ArrayList.php
- tests/Unit/CypherListTest.php
> Create a sensible error when fetch limit is being rewound + fixed off by one error

- src/Neo4j/Neo4jConnectionPool.php
> fix: resolving hosts does not check /etc/hosts in Neo4JConnectionPool

- src/Types/AbstractCypherSequence.php
> fix: Implicit conversion from float error

- src/Bolt/BoltConnection.php
Redone @stefanak-michal's PR from https://github.com/neo4j-php/neo4j-php-client/pull/206
> feat: Improve error handling in connection

- composer.json
- docker-compose.yml
> feat: Update bolt to 7.1.4

- src/ClientBuilder.php
- src/DriverFactory.php
- tests/Integration/ClientBuilderTest.php
- **refactor: Update method signature in DriverFactory to remove unused parameters**
- **feat: Add optional logging support to ClientBuilder**
- **fix: Update default values for optional parameters**
- **style: Remove unnecessary import of LoggerInterface**
- **test: Add logging capability to ClientBuilderTest**
> fix: Pass logger to ClientBuilder
